### ISSUE TITLE
Compatibility Issue with Lower Dart Versions

### ISSUE THREAD

**Issue by rajChokshiDeveloper710** [wmtrnsapanzaveri/snug_logger#3]
I am currently working on a project with Dart version 2.16.2  , and I've encountered compatibility issues with the snug_logger library. Could you please downgrade the version to atleast 2.16.2 .

**Comment by wm-jenildgohel** [comment]
Hey @rajChokshiDeveloper710, thanks for pointing this out! We're currently working on adding support for legacy Dart versions. In the next release, we'll make sure to resolve this issue. Keep coding with confidence, and stay tuned for updates! :)

**Comment by wmtrnsapanzaveri** [comment]
Hey @rajChokshiDeveloper710, we've added support for older versions. Now you can time travel back to the good ol' days of coding. Stay young, stay updated!
